# Generated by Django 5.2.1 on 2025-05-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Donor's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Donor's last name", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="Donor's email address for receipt (optional)", max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stripe_checkout_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
