# Generated by Django 5.2.1 on 2025-05-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(max_length=300)),
                ('image_alt', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('article', models.TextField()),
            ],
        ),
    ]
